name: Copy File Between Repositories

on:
  push:
    branches:
      - main  # または、メインブランチの名前

jobs:
  copyFile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy File
      run: |
        # ファイルを指定のディレクトリにコピーするコマンド
        cp path/to/file.txt /path/to/destination

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Automatically copied file"
        git push https://${{ secrets.DESTINATION_REPO_TOKEN }}@github.com/USERNAME/DESTINATION_REPO.git HEAD:main
