name: Clone Repository
on: [push]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@v3
     with:
       path: main

   - name: Checkout kakisoftwork1/RepositoryLinkSample02
     uses: actions/checkout@v3
     with:
       repository: kakisoftwork1/RepositoryLinkSample02
       path: RepositoryLinkSample02
