name: GitHub Actions Demo
on: [push]
jobs:
  #=======================
  #     変数の値を出力
  #=======================
  action01:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "github.event_name - ${{ github.event_name }} "    # push
      - run: echo "runner.os         - ${{ runner.os }}         "    # Linux
      - run: echo "github.ref        - ${{ github.ref }}        "    # ref/heads/main
      - run: echo "github.repository - ${{ github.repository }} "    # kakisoftwork1/RepositoryLinkSample01
      - run: echo "github.workspace  - ${{ github.workspace }}  "    # ''
      - run: echo "job.status        - ${{ job.status }}        "    # success

  #=======================
  #        基本操作
  #=======================
  action02:
    runs-on: ubuntu-22.04
    steps:
      - run: pwd
      - run: ls
      - run: ls -a

  #=======================
  #
  #=======================
  action03:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls
